package com.effort.common;

public enum WebDriversEnum {
	LOGIN_DRIVER, FORGOT_PASSWORD_DRIVER, BUY_INVESTMENT_DRIVER, CUSTUMERTEST_DRIVER, EMPLOYEE_CREATION_DRIVER,
	ENTITIES_PROCESS_DRIVER, ENTITIES_SUBMISSION_DRIVER, CUSTOMERS_EXPORTS_DRIVER, EMPLOYEE_EXPORTS_DRIVER, 
	ENTITIES_EXPORTS_DRIVER, FORM_EXPORTS_DRIVER, LEAVES_EXPORT_DRIVER, EMPLOYEE_FILTERS_DRIVER, ENTITY_FILTERS_DRIVER, 
	LEAVES_FILTERS_DRIVER, CUSTOMER_BULKUPLOAD_DRIVER, EMPLOYEE_BULKUPLOAD, LIST_BULKUPLOAD, ROUTE_PLAN_BULKUPLOADS,
	LEAVES_DRIVER, WEB_APP_LOGIN_DRIVER, ACTION_PROCESS_DRIVER, ADD_WORK_PROCESS_DRIVER, WORK_PROCESS_CREATION_DRIVER,
	FORMS_DRIVER, FORM_SUBMISSION_DRIVER, ROUTE_PLANS_DRIVER;
}
