Sleep(1000)
ControlFocus("Open","","Edit1")
Sleep(1000)
ControlSetText("Open","","Edit1","C:\SeleniumWorkSpace\EFFORT_WEB_LIVE\MediaFiles\Documentfile.xlsx")
Sleep(1000)
ControlClick("Open","","Button1")