Sleep(1000)
ControlFocus("Open","","Edit1")
Sleep(1000)
ControlSetText("Open","","Edit1","C:\Users\srinu\OneDrive\Desktop\GitProject\Effort-Automation\MediaFiles\image.jpg")
Sleep(1000)
ControlClick("Open","","Button1")