Sleep(1000)
ControlFocus("Open","","Edit1")
Sleep(1000)
ControlSetText("Open","","Edit1","C:\Users\Tejovani\Effort auto\Effort-Automation\AutoIt\VideoPicker.au3")
Sleep(1000)
ControlClick("Open","","Button1")