Sleep(1000)
ControlFocus("Open","","Edit1")
Sleep(1000)
ControlSetText("Open","","Edit1","C:\Users\Tejovani\EffortAuto\Effort-Automation\MediaFiles\Video.mp4")
Sleep(1000)
ControlClick("Open","","Button1")